# Generated by Django 4.2.27 on 2025-12-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
    ]
