# Generated by Django 4.2.27 on 2025-12-06 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_auto_20251206_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('time_marked', models.TimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('QR_SCAN', 'QR Code Scan'), ('MANUAL', 'Manual Entry'), ('BULK', 'Bulk Import')], max_length=20)),
                ('qr_data', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date', '-time_marked'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('time_marked', models.TimeField(auto_now_add=True)),
                ('is_present', models.BooleanField(default=False)),
                ('qr_scanned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date', 'student__last_name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='marked_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_app.teacher'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.student'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.student'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_app.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together={('student', 'date')},
        ),
    ]
